### PR TITLE
Add Iubenda module and use it

### LINKED ISSUE #120: Improve cache busting on Hugo JSON
I created a simple JSON shortcode to pull in API data

/content/en/info/privacy-policy.md
```
{{< json "https://www.iubenda.com/api/privacy-policy/xxxxxx?20200704" >}}
```

and 
/layouts/shortcodes/json.html
```
{{ with .Get 0 }}
    {{ $data := getJSON . }}
    <div class="max-w-4xl my-32">
        {{ $data.content | safeHTML }}
    </div>
{{ end }}
```

Note in the markdown document I'm using a query string (I put in the date, but could be anything) so that if I change the content from the API, Hugo updates the content pulled into the page. It does not update otherwise. 

**We certainly want the data cached so it's not pulling in on each build**, but using a query string means that each time the content is updated from the API, the query string needs to be adjusted, which could be cumbersome and error prone. 

This issue is meant to explore if there is a better method for breaking the cache.

### PR DESCRIPTION
**Pull request by regisphilibert**
Fixes #120

### CODE REVIEW

**Comment by regisphilibert** [comment]
Everything looks great. The only problem we have is the following:

As we are using environment variable to print the Iubenda stuff and of course, don't print anything when the variables are not found, they if the env vars are not set on my machine, Hugo will not print the iubenda and will strip the produced classes from `hugo_stats.json`.

This is problematic as this means I need the vars on my machine when running `nn deploy`.

To keep the obfuscation in place, we would need a sort of `.env` file equivalent but for Hugo... Any suggestion @budparr ?

**Comment by budparr** [comment]
I'll think about it the env. Not sure.

Note, this won't work on our production site until #108 (and therefore #109 ) is fixed.

**Comment by budparr** [comment]
In fact, you'll note this in the console: `Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy.`

**Comment by regisphilibert** [comment]
Yes as you guess we don't use the style tag on our site as it would prevent us from using tailwind etc...

It's just an option for users to add an `assets/tnd-iubenda/style.css` to their asset dir and let Hugo handle the rest.

**Comment by budparr** [comment]
doesn't what I did work?
/* purgecss start ignore */

/* purgecss end ignore */

**Comment by regisphilibert** [comment]
Sorry I didn't notice.

**Comment by budparr** [comment]
I think it's generally better to keep the whitelist in the file (i.e. use the comments) when possible.

**Comment by regisphilibert** [comment]
I agree, I didn't notice the comments in the css file and completely forgot about this possibility. Just reverted.

**Pull request merged**
