### PR TITLE
Use Hugo transformation

### LINKED ISSUE #116: Try and use Hugo image transformation
We need to the upload directory of the CMS to be in reach of Hugo Image transformation either through:

### Hugo Pipes
This means we need to move `static/uploads` to `assets/upload`.
This also means we have to make sure every assets is published through Hugo Pipe and a `.RelPermalink` is used.

### A Page Bundle
This means we need to move `static/uploads` to said Bundle.
The advantage of using a Bundle is that we can now choose if we want the resources to be automatically published (even though `.RelPermalink` is not produced), OR not, just like the above.

### PR DESCRIPTION
**Pull request by regisphilibert**
Set up testing page at /images

Fixes #116

### CODE REVIEW

**Comment by regisphilibert** [comment]
@budparr I'm getting mixed results when transforming images with targeted size not so different than the original one.

Bear in mind that if an image with an original size of 577 is to be resize to 600, we do use the `.Resize` method but to its orignal size so we can test the `q95` setting (let's call this too_small scenario)

What is a bit alarming is that if you look at this test page: https://deploy-preview-125--thenewdynamic.netlify.app/images/

You can inspect network imgs and notice that some transformed images (like regis.jpeg) are heavier than the original 🤷 .

This might simply mean that we should use the original image when encountering the too_small scenario, but also questions the how reliable is Hugo's transformations in term of image size optimization.

What would be ideal is to setup a test repo to compare Original + Hugo Transformed + Imgix Transformed.

**Comment by budparr** [comment]
I think it's worth doing the test repo if you have the time, because this will certainly inform our client work as well

**Comment by regisphilibert** [comment]
Here it is: https://tnd-modules.netlify.app/images/

So we're using our usual imgix defaults at 95 quality and 600px width
And we're using Hugo's q95 and 600px width with the `lanczos` filter, because default `box` is really poor when dealing with charts and fonts...

The quality is very similar on both, but for the file weight Hugo systematically loses, getting from 1.3 to 2 times bigger than imix file.

**Comment by budparr** [comment]
interesting. Is this something to bring up to BEP, or is it just a general limitation?

**Comment by regisphilibert** [comment]
Actually scratch that after looking closer, results are very similar. Hugo still loses but by a mere 10% I would say.

**Comment by budparr** [comment]
And, depending on the image size (that is, for smaller images), the size difference may be offset by not making an HTTP request (only valid until we're in an H2 world).

**Comment by regisphilibert** [comment]
>  the size difference may be offset by not making an HTTP

You mean calling the image hash thingy?

**Comment by budparr** [comment]
No. When we load an image from imgix we're making an HTTP request to do so, which entails a performance cost

**Comment by regisphilibert** [comment]
I see.

**Pull request merged**
