### PR TITLE
HUGE Announcement

### PR DESCRIPTION
**Pull request by regisphilibert**

### CODE REVIEW

**Comment by regisphilibert** [comment]
@budparr this is it: https://deploy-preview-180--thenewdynamic.netlify.app/article/introducing-huge/

The idea is to share only the first part (before feature listing) on the Hugo Discourse, inviting users to read the blog post for more info.

**Comment by budparr** [comment]
I ❤️ this. Note that it's "JSON+LD" not "jsonld" as you have it.

**Comment by regisphilibert** [comment]
@budparr it's done on my end, would you mind giving it a quick "english" check? 🙏

**Comment by budparr** [comment]
Looks good to me

**Pull request merged**
