### PR TITLE
Edit article intro

### PR DESCRIPTION
**Pull request by budparr**
These edits are meant to make the intro a bit more friendly for people who don't know Hugo necessarily.

### CODE REVIEW

**Comment by budparr** [comment]
@regisphilibert I've made my edits. I'm thinking our reader for the intro could be non-technical clients, etc. and just wanted to make that part more suitable. So, apologies from the marketing department for trampling on your voice a bit.

Can we get a code image for the intro instead of the text?

**Comment by budparr** [comment]
https://deploy-preview-172--thenewdynamic.netlify.app/article/toward-using-a-headless-cms-with-hugo-part-1/

**Comment by regisphilibert** [comment]
> Can we get a code image for the intro instead of the text?

My first intention, but couldn't find a piece of code that made sense here...

**Comment by regisphilibert** [comment]
This is great! Thanks a ton @budparr

**Pull request merged**
