### PR TITLE
Add critical inline style to headers

### LINKED ISSUE #109: Hash Inline styles
Critical CSS is great for performance, but for security we need to ensure any inline styles are explicitly allowed in our content security policy. 

We need to generate a hash of generated styles (I believe we can do this with Hugo's integrity function), but the hash goes into the generated Content Security Policy header:

e.g.
`Content-Security-Policy: style-src 'sha256-B2yPHKaXnvFWtRChIbabYmUBFZdVfKKXHbWtWidDVF8='`

This issue depends on #108

### PR DESCRIPTION
**Pull request by regisphilibert**
Upgrade Headers module

Fixes #109

### CODE REVIEW

**Comment by regisphilibert** [comment]
Alright this was a bit tricky as this could not be declared as a new header, but add to be part of the CSP header. As there is no way to merge two headers (one from the config, one from the returning partials) I moved the CSP details from the config to the returning partial.
We're still using yaml syntax though, so should be easy to maintain: 

https://github.com/theNewDynamic/thenewdynamic.com/blob/68333fb4e4b0e44ebe632d8551769fe7fee43a9e/layouts/partials/tnd-headers/AddHeaderGroups.html#L2-L12

**Comment by budparr** [comment]
So how easily editable is the CSP now?

**Comment by budparr** [comment]
Just checking...
> could not be declared as a new header, 
because the script-src hashes were specific to the page they show up on? What if an inline script were added to a partial and the partial was used on multiple pages?

**Comment by regisphilibert** [comment]
No this means we declared two headers with the same field `Content-Security-Policy` and Netlify just picked the last one (overwriting the first). So the `script-src` had to be added to the same header values. 

> So how easily editable is the CSP now?

Through here a project's partials: https://github.com/theNewDynamic/thenewdynamic.com/blob/68333fb4e4b0e44ebe632d8551769fe7fee43a9e/layouts/partials/tnd-headers/AddHeaderGroups.html#L2-L12

**Comment by budparr** [comment]
Cool.

**Pull request merged**
