### PR TITLE
Improve search icon alignment

### LINKED ISSUE #29: Improve search icon alignment
this feels off to me. 

I think the magnifier should be more inline with the text items, therefore should extend down as though it were a letter with a descender.

I'm not sure how to do this in CSS without upsetting the padding or margins of things around it (maybe the answer is in the SVG???).

### PR DESCRIPTION
**Pull request by mountainbug95**
Fixes #29

### CODE REVIEW

**Comment by mountainbug95** [comment]
I've also added a cdn for alpinejs. It was not working fo me for some reason.

**Comment by budparr** [comment]
Thanks, @mountainbug95, but Alpine is loaded via NPM. We have an issue with Webpack loading concurrently with Hugo that sometimes breaks the JS build, so that's likely your JS issue. You can just run `npm hugo` because I don't think in this instance you need to change any scripts. 

Can you remove the Alpine, please? We would rarely, if ever, load external scripts from a CDN.

**Comment by budparr** [comment]
The icon looks good though, thank you.

**Comment by mountainbug95** [comment]
@budparr okay, fixed

**Pull request merged**
