### PR TITLE
Typo in the article

### PR DESCRIPTION
**Pull request by enguerran**
I don't see why it's not the same repository here as in the example above, i.e. `github.com/twbs/icons`.

Thank you for the article and your work.

### CODE REVIEW

**Review by DirtyF — APPROVED** [review]

**Comment by enguerran** [comment]
Reading the article, I realize that there is the same ambiguity everywhere even in the header image.

I redrew the screenshot for the header (I didn't find the exact same color scheme).

hugo-modules-featured

**Comment by enguerran** [comment]
How about adding the `toml` version of module management? I've spent some time trying to figure out how to do this.

```toml
[module]
[[module.imports]]
path = "github.com/refactoringui/heroicons"
[[module.imports.mounts]]
source = "src/solid/shopping-cart.svg"
target = "assets/icons/cart.svg"
[[module.imports]]
path = "github.com/twbs/icons"
[[module.imports.mounts]]
source = "icons"
target = "assets/icons"
```

**Review by regisphilibert — APPROVED** [review]
Hi @enguerran yes thanks for pointing this out, not sure why the initial back and forth but thanks for correcting. 

For your image suggestion, I'll ignore it. A this is the first thing potential readers see on social media etc... before even reading the description I'll favor illustration over logic. People intuitively understand that `github.com/twbs/bootstrap` points to the famous library and uses its icons, while `github.com/twbs/icon` does not look too familiar to any reader and the icons being hosted on a standalone repo is not very relevant at this point.

As for `toml` vs `yaml` I'm not opinionated but I don't want to provide examples in each hugo available config languages... I guess we could find a way to make readers aware of tools like https://toolkit.site/format.html but not sure how...

**Comment by enguerran** [comment]
Thank you for the welcome and your explanations about the configuration file format. But also for the illustration, your explanations are very clear and I am glad to learn from your very interesting experience.

**Pull request merged**
